### PR TITLE
Changes to get PY2020/Jetson-Can branch to compile

### PR DESCRIPTION
**Pull request by nhatch**
Adds a couple of methods (which were already implemented) to the
corresponding header file. Also moves PortTemplate.c to Port.c and makes
it compile-able.

I'm guessing there's something wrong with these changes to
PortTemplate.c, but I don't understand how we're supposed to implement
Port.c. Possibilities included:

* Put it in this directory (in the git submodule)? But then it's
impossible to track changes to Port.c; the submodule commit will always
be dirty.

* Make a new branch of this repo and checkout that branch in the
container repo? But that invites merge conflicts, and it doesn't seem to
be what people have done (I don't see many branches on this repo).

* Put all of the different "subclasses" of PortTemplate.c in this repo
with unique names, and choose the right one to compile using CMakeLists
in the container repo? That would work, but then I don't see why we need
a PortTemplate.c at all. (People wanting to implement a new Port could
just copy one of the existing ones.)

I'm happy to make changes; all I really want is for the Jetson-Can
branch on PY2020 to compile.

### CODE REVIEW

**Comment by DylanTomberlin** [comment]
Hi Nathan,
Here was my plan for implementing various Port[chipname].c files.  Not sure what standard practice is but I think this should work. Correct me if I'm wrong.

1.) Create Port[chipname].c file in a folder of port files
2.) Add #if CHIP_TYPE == CHIP_TYPE_xxx to top of C file, #endif at the bottom
3.) Implement functs whose prototypes are in port.h
4.) Compile, passing in constant to gcc using  -D CHIP_TYPE=CHIP_TYPE_xxx . I've never used this flag before, so may be incorrect usage.  Maybe it needs a real number, rather than another macro define? I sketched out some constants in port.h which should replace CHIP_TYPE_xxx with a number.

If I'm not mistaken, this should make it so there is only one place in the code trying to implement these functs.  PortTemplate.c was just supposed to be an example of this, which could be copied by the person who is porting.  Does my method make sense and sound reasonable?

**Comment by Baldstrom** [comment]
I was able to compile using the `-D ` option that Dylan mentioned.

**Review by DylanTomberlin — CHANGES_REQUESTED** [review]
Per previous comments, I think our plan for using the preprocessor to handle different ports will work. I will document this on the Readme.md.  The other changes you made look good, so if you add back the #if and #endif statements, I can merge these changes in. Thanks!

**Comment by nhatch** [comment]
Comments addressed!

Another possibility to consider:

1. Create Port[chipname].c in a folder of port files
2. Don't have any preprocessor directives and don't pass in any constants to gcc
3. Ensure while building that only one of the port .o objects is linked into the final executable

That last step is almost automatic, since when you're building an executable for any given port, you just list the .c or .cpp files that the executable depends on (and all you have to do is include the proper port file in that list). For example, in CMakeLists.txt in the Jetson-Can branch, we can just do

```
add_executable(Rover
        Rover.cpp
        CommandLineOptions.cpp
        Globals.cpp
        Network.cpp
        ParseCAN.cpp
        HindsightCAN/CANPacket.c
        HindsightCAN/CANCommon.c
        HindsightCAN/PortTemplate.c)
```

and don't have to worry about how to set command-line flags defining preprocessor constants. (For now I worked around this by just using a #define inside PortTemplate.c.)

**Comment by DylanTomberlin** [comment]
That makes sense. I'll talk with @Jaden and see what the plan is for compiling all the projects, if we're going to write makefiles or leave it up to members themselves.

**Comment by nhatch** [comment]
I figured out how to set variables using cmake in the PY2020/Jetson-Can branch, so I removed the #define from this pull request. Hopefully the rest of it can be merged now?

**Review by DylanTomberlin — APPROVED** [review]

**Pull request merged**
